### ISSUE TITLE
No valid data?

### ISSUE THREAD

**Issue by kralikba** [Victor-Mo/IRT-ESP#7]
Hello,

I've received an iRT board from bbqkees with the Wemos installed but I can't seem to get valid data out of the system. The ESP has IRT-ESP version 1.9.8.20073113 pre-flashed. I've set txmode 4 but otherwise everything is the default.

I have a Buderus system: a Logamax plus GB112 (looks like an UBA 1.5), a Logamatic 4121 controller, a MEC2 remote control/thermostat installed inside the heated area, connected to the controller with approx 5 m of a twisted pair of thick stranded wire, and the solar module. I've tried tapping the wire pair going to the thermostat, directly connecting the esp module to the controller's "thermostat port" and connecting only the esp module to the "thermostat port". 

I've tried "reversing the polarity" (I'm not sure whether that matters).

I do not get any valid data any way, just CRC errors. When the MEC2 is connected, `log j` shows a lot of telegrams: (otherwise just a couple short ones)

```
(00:08:47.679) irt_rawTelegram: 01: 00
(00:08:47.688) irt_rawTelegram: 01: 00
(00:08:47.697) irt_rawTelegram: 01: 00
(00:08:47.706) irt_rawTelegram: 01: 00
(00:08:47.714) irt_rawTelegram: 01: 00
(00:08:47.743) irt_rawTelegram: 05: 80 80 F8 78 80
(00:08:47.744) irt_otherTelegram: 05: 80 80 F8 78 80
(00:08:47.870) irt_rawTelegram: 06: 80 80 80 80 F8 80
(00:08:47.871) irt_otherTelegram: 06: 80 80 80 80 F8 80
(00:08:47.879) irt_rawTelegram: 01: 00
(00:08:47.888) irt_rawTelegram: 01: 00
(00:08:47.897) irt_rawTelegram: 01: 00
(00:08:47.906) irt_rawTelegram: 01: 00
(00:08:47.914) irt_rawTelegram: 01: 00
(00:08:47.943) irt_rawTelegram: 04: 80 F8 78 80
(00:08:47.944) irt_otherTelegram: 04: 80 F8 78 80
(00:08:48.062) irt_rawTelegram: 02: 80 80
(00:08:48.062) irt_crcErr1: 02: 80 80
(00:08:48.070) irt_rawTelegram: 01: 00
(00:08:48.075) irt_rawTelegram: 01: 00
(00:08:48.079) irt_rawTelegram: 01: 00
(00:08:48.088) irt_rawTelegram: 01: 00
(00:08:48.100) irt_rawTelegram: 01: 78
(00:08:48.114) irt_rawTelegram: 03: 78 80 F8
(00:08:48.115) irt_crcErr1: 03: 78 80 F8
(00:08:48.123) irt_rawTelegram: 01: 00
(00:08:48.127) irt_rawTelegram: 01: 00
(00:08:48.143) irt_rawTelegram: 03: F8 78 80
(00:08:48.144) irt_crcErr1: 03: F8 78 80
(00:08:48.265) irt_rawTelegram: 03: 80 80 80
(00:08:48.265) irt_crcErr1: 03: 80 80 80
(00:08:48.275) irt_rawTelegram: 01: 78
(00:08:48.279) irt_rawTelegram: 01: 00
(00:08:48.297) irt_rawTelegram: 03: 80 F8 F8
(00:08:48.297) irt_crcErr1: 03: 80 F8 F8
(00:08:48.343) irt_rawTelegram: 0C: 80 F8 F8 80 F8 F8 F8 80 F8 F8 78 80
(00:08:48.344) irt_otherTelegram: 0C: 80 F8 F8 80 F8 F8 F8 80 F8 F8 78 80
```

This doesn't feel right. What could the problem be?

Thanks!
Barnabás

**Comment by Victor-Mo** [comment]
@kralikba That is quite a big setup. I am not familiar with the Logamatic 4121, but I have googled the instalation manual. It looks like only the connection between the Logamax plus GB112 and the Logamatic 4121 is using the iRT (UBA 1.x) protocol.

I think the best option is to connect it parallel to the boiler connection(Logamax plus GB112). Have a look at issue #6 there is a picture where the wires go. So leave the wires between the Logamax plus GB112 and the Logamatic 4121 in place and put the board parallel to this connection.

**Comment by kralikba** [comment]
@Victor-Mo thanks for the idea. It has never occurred to me that the room thermostat is not directly connected to the bus. Now that you gave me this idea, I've found some documentation about it - and it is communicating at a data rate of 1200 bps, which perfectly explains the F's and 8's.

**Comment by kralikba** [comment]
Thanks; i have connected it to the EMS/UBA port on the controller (turns out there is one clearly labelled as such) which goes to the boiler itself as well. (approx. 1,5 meters of wire to the boiler; 30 cm to the ESP; both connected/stuffed into the same screw terminal). I am getting _some_ data, but mostly CRC errors now:

```
System Logging set to Jabber mode

->
(00:06:21.448) irt_rawTelegram: 3F: 01 01 FE F0 F0 01 01 1B 1B 9E 9E 01 FE F0 F0 01 01 1C 1C 82 82 02 FD F0 F0 01 01 1D 1D 86 86 1B E4 AB AB 52 52 25 25 9B 9B 01 FE F0 F0 82 82 D2 D2 8E 8E 42 BD F0 F0 01 01 21 21 76 76 5B A4
73:52 78:06 | 82:00 83:02 84:55 90:8A 93:FF 96:7F 97:00 A3:03 A4:14 A6:14 A8:75 AA:FD AB:01 C9:00   0H
(00:06:21.568) irt_rawTelegram: 01: 02
(00:06:21.688) irt_rawTelegram: 01: 03
(00:06:21.788) irt_rawTelegram: 01: 00
(00:06:22.888) irt_rawTelegram: 3C: 01 01 FE 82 82 01 01 1B 1B EC EC 00 FF 83 83 01 01 1C 1C F1 F1 02 FD 93 93 01 01 1D 1D E5 E5 FF 00 90 90 52 52 25 25 A0 A0 8A 75 C9 C9 82 82 D2 D2 B7 B7 00 FF 96 96 01 01 21 10 80
(00:06:22.891) irt_crcErr3: 3C: 01 01 FE 82 82 01 01 1B 1B EC EC 00 FF 83 83 01 01 1C 1C F1 F1 02 FD 93 93 01 01 1D 1D E5 E5 FF 00 90 90 52 52 25 25 A0 A0 8A 75 C9 C9 82 82 D2 D2 B7 B7 00 FF 96 96 01 01 21 10 80
(00:06:23.008) irt_rawTelegram: 01: 02
(00:06:23.128) irt_rawTelegram: 01: 03
(00:06:23.229) irt_rawTelegram: 01: 00
(00:06:23.989) irt_rawTelegram: 26: 01 01 FE 97 97 01 01 1B 1B F9 F9 00 FF 84 84 01 01 1C 1C F6 F6 55 AA 73 73 52 52 25 25 43 43 78 78 06 06 00 95 74
(00:06:23.990) irt_crcErr3: 26: 01 01 FE 97 97 01 01 1B 1B F9 F9 00 FF 84 84 01 01 1C 1C F6 F6 55 AA 73 73 52 52 25 25 43 43 78 78 06 06 00 95 74
(00:06:24.109) irt_rawTelegram: 01: 02
(00:06:24.229) irt_rawTelegram: 01: 03
(00:06:24.329) irt_rawTelegram: 01: 00
(00:06:25.109) irt_rawTelegram: 26: 01 01 FE 73 73 52 52 25 25 43 43 78 78 02 02 00 00 7C 7C 73 73 52 52 25 25 43 43 78 78 00 FF FF AF AF 00 00 D2 63
(00:06:25.111) irt_crcErr3: 26: 01 01 FE 73 73 52 52 25 25 43 43 78 78 02 02 00 00 7C 7C 73 73 52 52 25 25 43 43 78 78 00 FF FF AF AF 00 00 D2 63
(00:06:25.229) irt_rawTelegram: 01: 02
(00:06:25.349) irt_rawTelegram: 01: 03
(00:06:25.449) irt_rawTelegram: 01: 00
(00:06:26.330) irt_rawTelegram: 2B: 01 01 FE 73 73 52 52 25 25 43 43 78 78 01 01 FF FF AD AD 01 01 05 05 25 25 9F 9F 73 73 52 52 25 25 43 78 FF 07 FF A1 07 00 21 83
(00:06:26.332) irt_crcErr3: 2B: 01 01 FE 73 73 52 52 25 25 43 43 78 78 01 01 FF FF AD AD 01 01 05 05 25 25 9F 9F 73 73 52 52 25 25 43 78 FF 07 FF A1 07 00 21 83
(00:06:26.430) irt_rawTelegram: 01: 02
(00:06:26.550) irt_rawTelegram: 01: 03
(00:06:26.670) irt_rawTelegram: 01: 00
(00:06:27.771) irt_rawTelegram: 3F: 01 01 FE F0 F0 1F 1F FE FE 1D 1D 82 7D F0 F0 1F 1F FF FF 19 19 D3 2C A4 A4 05 05 25 25 3A 3A 14 EB A6 A6 52 52 25 25 96 96 14 EB A8 A8 07 07 FF FF 71 71 75 8A A3 A3 00 00 21 21 27 27 03 FC
(00:06:27.871) irt_rawTelegram: 01: 02
(00:06:27.991) irt_rawTelegram: 01: 03
(00:06:28.111) irt_rawTelegram: 01: 00
(00:06:29.251) irt_rawTelegram: 3F: 01 01 FE F0 F0 01 01 1B 1B 9E 9E 01 FE F0 F0 01 01 1E 1E 8A 8A 4D B2 F0 F0 01 01 1F 1F 8E 8E 0F F0 AA AA 52 52 25 25 9A 9A FD 02 F0 F0 82 82 CC CC F6 F6 01 FE F0 F0 82 82 CD CD F2 F2 20 DF
(00:06:29.371) irt_rawTelegram: 01: 02
(00:06:29.471) irt_rawTelegram: 01: 03
(00:06:29.591) irt_rawTelegram: 01: 00
```

**Comment by kralikba** [comment]
Now that the warm water is being prepared for the evening, I've reconnected the device. It is still mostly showing CRC errors butt some of the boiler-related data now seems correct: 

```
->
Error! Unable to read the iRT bus.
info

IRT-ESP system status:
  System logging set to None
  LED: on, Listen mode: off

iRT Bus stats:
  No connection can be made to the iRT bus
  Rx: # successful read requests=727, # CRC errors=138

Boiler stats:
  Warm Water activated: off
  Warm Water selected temperature: 0 C
  Warm Water current temperature: 117.0 C
  Warm Water 3-way valve: on
  Selected flow temperature: 0 C
  Current flow temperature: 70.0 C
  Return temperature: 64.0 C
  Gas: on
  Boiler pump: on
  Fan: on
  Ignition: off
  Burner selected max power: 0 %
  System service code: =H (91)
  Heating temperature setting on the boiler: 0 C
  Outside temperature: 0.0 C
  Boiler temperature: 0.0 C
  Pump modulation: 0 %
  Burner # starts: 0 times
  Total burner operating time: 0 days 0 hours 0 minutes
```

The web interface still just says "EMS Bus is not connected."

**Comment by Victor-Mo** [comment]
@kralikba Good to see that it is at least doing 'something'. But i think the signaling from the 'Logamatic 4121' is slightly different. Maybe the message are slightly longer ?. Could you make a longer 'log j' log file ? Just leave it running for 10 minutes.  You can attach a file to the issue.

The 117 is not correct, but the message i use for the warm water temperature, 0xA8 seems to report it (A8 A8 07 07 FF FF 71 71 75 8A) the 0x75 = 117. But it could be there is another message with the right value.

**Comment by kralikba** [comment]
I've attached a log:

https://gist.github.com/kralikba/219e08662b244e375e99a31539e3465c

**Comment by Victor-Mo** [comment]
Hi @kralikba ,

I have had a quick look at the log you provided. It looks like it is not detecting all the bytes on the long messages. I am not sure if it simply is not correctly detecting the bytes or if the ESP has problems keeping up with the data. It mostly happens at the end of the data.

If i manually 'fix' the data it seems to contain all the messages. So i do not thing the langue they 'speak' between the 4142 and the UBA is different.

Currently it completely ignores all the data if it detects a problem in the complete string. I will have a look if i can make something that at least processes the good part of the data. That should give you a working system.

Does the 117 degrees water temperature change at all ? Is there any relation with the real temperature ? like divided by two ? Is the boiler used for Hot tapwater ?

**Comment by kralikba** [comment]
Hi, 
The 117 degree doesn't seem to change at all. The hot water setpoint is 56 degrees, so it is not a double of that.
The hot water is produced by the boiler, but indirectly, through a storage tank, which is also heated by the solar collector.

**Comment by kralikba** [comment]
I've tried cutting the wire as short as physically possible but the general behaviour is the same. Do you have any hardware modification ideas which might help a bit?

**Comment by Victor-Mo** [comment]
Hi @kralikba ,

Sorry for the delay in responding, but it has been a busy week.

I have not had time to look at the trace, if I can find another location for the hot water.

I am not 100% sure about the board you have. There should be a resistor of 1 MOhm (I think R22). Increase this to 1,5 MOhm or even 2 MOhm may help with improving the detection. Because of the slow speed (4800 Baud) the length of the bus and tap connection is not really critical.

**Comment by kralikba** [comment]
Hi,
Finally I managed to look at this. It was 1,5 MOhm; I have replaced it with a 2,2 MOhm one and now there are next to no CRC errors. However, the data still doesn't look valid: the web interface is "green" but reports incorrect information. See the below log if you have time. Thanks!

https://gist.github.com/kralikba/e50f88c23178a876dd8d15c455532ade

**Comment by kralikba** [comment]
![image](https://user-images.githubusercontent.com/1148937/96019256-94b31600-0e4c-11eb-85ed-37229e974e60.png)

**Comment by Victor-Mo** [comment]
@kralikba Good news that the board is working now, a few CRC errors is normal. I had a quick look at you log file and the data looks solid. There are a few other, unknown to me, messages. So I will have a better look at the log file.

The webgui needs some work. But I can see the flow and return temperature is reported. These values need a correction. For example in your picture it reports 18 degrees, but it actually is 26 degrees. I am currently working on a conversion table.

I have been reading in the installation manual of your boiler. It does not have a warm water sensor in the boiler itself, but an external sensor can be connected. Can you confirm it is connected ?

**Comment by kralikba** [comment]
Yes it is, but to the Logamatic controller. Maybe it doesn't show up on the UBA bus? From what I've understood, other components of this control system are connected to a separate internal bus.

**Comment by kralikba** [comment]
That 26 degrees is correct as far as I remember!

**Comment by Victor-Mo** [comment]
I have created a new version, v1.9.10, that has a correction on the reported temperatures. I also cleaned-up the web GUI.

But the iRT protocol is very basic. It is just to control the boiler. I think you will only get the Flow and return temp. and if the boiler is running. I do not think the logamatic controller will publish any 'extra' information on the iRT bus to the boiler.

**Comment by Victor-Mo** [comment]
Closing the issue, feel free to reopen if necessary.
